sonar.projectKey=TuroYT_snowshare_4db21712-11b7-4dfd-96ba-6cfd0c472d4e
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sources=src
sonar.exclusions=src/generated/**,src/__tests__/**,src/test-utils.ts
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**
sonar.coverage.exclusions=src/components/**,src/app/**/page.tsx,src/app/**/layout.tsx,src/lib/openapi.ts,src/lib/prisma.ts,src/i18n/client.ts,src/lib/providers-icons.tsx
