name: "CI"

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run lint

  test:
    name: Test
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm test -- --ci --coverage --coverageReporters=text-summary

  build:
    name: Docker Build
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build
