name: Semgrep

on:
  push:
    branches: [canary]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: [self-hosted]
    if: github.event.pull_request.draft == false
    timeout-minutes: 20
    container:
      image: returntocorp/semgrep
    steps:
      - name: Fix workspace permissions
        run: chown -R "$(id -u):$(id -g)" "$GITHUB_WORKSPACE"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: semgrep ci --timeout 60 --timeout-threshold 3 --max-memory 5000 --oss-only
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
